# CHAPTER 4 NumPy Basics: Arrays and Vectorized Computation

In [4]:
def squares (values):
    result = []
    for i in values:
        result.append(i*i)
        return result 

In [5]:
to_squares = range(10000)
print(to_squares)

range(0, 10000)


# time how long it takes to repeatedly square them all

In [3]:
#it is magic functoion
%timeit squares(to_squares) 

479 ns ± 30.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Using NumPy and vectorized arrays:

In [6]:
import numpy as np
array_to_squares = np.arange(0,10)
array_to_squares ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [5]:
%timeit array_to_squares ** 2

1.14 µs ± 252 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Creating NumPy arrays and performing basic array operations

In [8]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [9]:
%timeit arr

51.2 ns ± 0.354 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [7]:
type(arr)

numpy.ndarray

In [8]:
np.size(arr)

6

In [8]:
np.shape(arr)

(6,)

In [9]:
arr.dtype

dtype('int32')

In [11]:
testArr = np.array([1,2,3,4,65] ,dtype='float32')
testArr

array([ 1.,  2.,  3.,  4., 65.], dtype=float32)

In [12]:
testArr = np.array([1,2,3,4,.65] )
testArr

array([1.  , 2.  , 3.  , 4.  , 0.65])

In [13]:
arr.ndim

1

In [14]:
testArr.ndim

1

In [15]:
np.array(range(13))


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [16]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
np.arange(0,34,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [18]:
np.arange(34,0,-3)

array([34, 31, 28, 25, 22, 19, 16, 13, 10,  7,  4,  1])

In [19]:
np.linspace(0,10,3) # it distrbute data equally

array([ 0.,  5., 10.])

In [20]:
data =([[ 0.9526, -0.246 , -0.8856],
         [ 0.5639, 0.2379, 0.9104]])
data

[[0.9526, -0.246, -0.8856], [0.5639, 0.2379, 0.9104]]

In [21]:
ar1 =np.array(data)
ar1*12

array([[ 11.4312,  -2.952 , -10.6272],
       [  6.7668,   2.8548,  10.9248]])

In [22]:
ar1+ar1

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [23]:
data1 = [6., 7.5, 8., 0., 1.]
data1

[6.0, 7.5, 8.0, 0.0, 1.0]

In [24]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [26]:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2+arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [28]:
arr2.ndim

2

In [29]:
arr2.shape

(2, 4)

In [30]:
arr2.dtype

dtype('int32')

In [31]:
np.zeros(13)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.empty((2, 3, 3))

array([[[2.05833592e-312, 2.05833592e-312, 6.79038653e-313],
        [6.79038653e-313, 1.14587773e-312, 9.33678148e-313],
        [1.16709769e-312, 1.12465777e-312, 6.79038653e-313]],

       [[9.76118064e-313, 6.79038653e-313, 9.76118064e-313],
        [6.79038653e-313, 9.76118064e-313, 2.12199580e-313],
        [2.05833592e-312, 2.05833592e-312, 2.13621350e-306]]])

In [34]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
np.ones((2,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [41]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types for ndarrays

In [42]:
arr1 = np.array ([1,2,3] ,dtype = np.float64)
arr1.dtype

dtype('float64')

In [43]:
arr2 = np.array ([1,2,3] ,dtype = np.int32)
arr2.dtype

dtype('int32')

In [44]:
arr1 = np.array ([1,2,3] ,dtype = np.complex64)
arr1.dtype

dtype('complex64')

In [45]:
arr1 = np.array ([1,2,3] ,dtype = np.bool)
arr1.dtype

dtype('bool')

In [47]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [48]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

# Operations between Arrays and Scalars

In [54]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [55]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [57]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [59]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [11]:
arr01 = np.arange (10)

In [12]:
arr01

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr01[0]

0

In [67]:
arr01[4:8]

array([4, 5, 6, 7])

In [68]:
arr01[4:8] = 34
arr01

array([ 0,  1,  2,  3, 34, 34, 34, 34,  8,  9])

In [69]:
arr_slice = arr01[4:8]
arr01

array([ 0,  1,  2,  3, 34, 34, 34, 34,  8,  9])

In [70]:
arr_slice

array([34, 34, 34, 34])

In [71]:
arr_slice[1] = 1234
arr01

array([   0,    1,    2,    3,   34, 1234,   34,   34,    8,    9])

In [83]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
arr2d[0][0]

1

In [78]:
arr2d[2,1]

8

In [81]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [82]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [84]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [89]:
old_values = arr3d[0].copy()

In [90]:
arr3d[0]=9
arr3d

array([[[ 9,  9,  9],
        [ 9,  9,  9]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [91]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
print(arr3d[1][0])
print(arr3d[1,0])

[7 8 9]
[7 8 9]


In [93]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [94]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [99]:
arr2d[:2,2:]

array([[3],
       [6]])

In [105]:
arr2d[1,:2 ]

array([4, 5])

In [106]:
arr2d[2,:1]

array([7])

In [107]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [108]:
arr2d[:2,1:]=0

In [109]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Boolean Indexing

In [16]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [17]:
from numpy import random

In [18]:
data

NameError: name 'data' is not defined

In [23]:
data = random.randn(7,4)

In [24]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [25]:
data

array([[ 0.85823682, -0.01359052, -0.4471115 , -0.94017225],
       [-1.07868919,  0.04001693, -1.64112697, -0.02802535],
       [-0.64385888, -1.67281687,  1.23841247, -1.66934034],
       [-1.13769526,  0.81889263, -0.24708396,  0.81403415],
       [ 1.03031518,  0.28981709,  0.7799016 ,  0.83135066],
       [ 0.77141415,  0.49540326,  1.04187302,  1.92549211],
       [ 1.41710166,  0.04023332,  0.06992292,  0.46797255]])

In [26]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [27]:
data [names == 'Bob']

array([[ 0.85823682, -0.01359052, -0.4471115 , -0.94017225],
       [-1.13769526,  0.81889263, -0.24708396,  0.81403415]])

In [28]:
data [names == 'Bob',:2]

array([[ 0.85823682, -0.01359052],
       [-1.13769526,  0.81889263]])

In [29]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [30]:
data[(names == 'Bob')]

array([[ 0.85823682, -0.01359052, -0.4471115 , -0.94017225],
       [-1.13769526,  0.81889263, -0.24708396,  0.81403415]])

In [31]:
mask = (names == 'Bob')|(names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [32]:
data[mask]

array([[ 0.85823682, -0.01359052, -0.4471115 , -0.94017225],
       [-0.64385888, -1.67281687,  1.23841247, -1.66934034],
       [-1.13769526,  0.81889263, -0.24708396,  0.81403415],
       [ 1.03031518,  0.28981709,  0.7799016 ,  0.83135066]])

In [33]:
data[data<0]=0
data

array([[0.85823682, 0.        , 0.        , 0.        ],
       [0.        , 0.04001693, 0.        , 0.        ],
       [0.        , 0.        , 1.23841247, 0.        ],
       [0.        , 0.81889263, 0.        , 0.81403415],
       [1.03031518, 0.28981709, 0.7799016 , 0.83135066],
       [0.77141415, 0.49540326, 1.04187302, 1.92549211],
       [1.41710166, 0.04023332, 0.06992292, 0.46797255]])

In [34]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.04001693, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.77141415, 0.49540326, 1.04187302, 1.92549211],
       [1.41710166, 0.04023332, 0.06992292, 0.46797255]])

# Fancy Indexing

In [145]:
arr = np.empty((8,4))

In [146]:
for i in range (4):
     arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [125]:
arr?

In [148]:
arr[[2,0,3,6]]

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [6., 6., 6., 6.]])

In [15]:
arr[[--5,-4,-2]]

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [16]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [22]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [23]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [24]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [26]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [36]:
arr = np.random.randn(6,3)
arr

array([[ 0.51953756, -0.03877886, -1.33714906],
       [-0.19683511,  0.58588121, -0.6709924 ],
       [-0.16759235, -1.09342691,  0.16073045],
       [-1.1114775 , -0.32758044, -0.42466511],
       [-0.43888575,  0.99905132, -0.09616075],
       [-1.12257591,  0.48644212,  0.99748022]])

In [38]:
np.dot(arr.T,arr)

array([[ 3.02493014, -0.57265837, -1.19509946],
       [-0.57265837,  2.88238143,  0.01124313],
       [-1.19509946,  0.01124313,  3.44858682]])